# Generated by Django 4.0.1 on 2022-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_photo_link', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('resume_link', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('twitter_link', models.CharField(max_length=200)),
                ('google_link', models.CharField(max_length=200)),
                ('instagram_link', models.CharField(max_length=200)),
            ],
        ),
    ]
