# Generated by Django 4.0.1 on 2022-01-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Basic_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('language', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='facebook_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='google_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='instagram_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='personal_photo_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='resume_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='twitter_link',
            field=models.TextField(),
        ),
    ]
