# Generated by Django 4.0.1 on 2022-01-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about_basic_information_alter_firstsection_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_basic_information',
            old_name='name',
            new_name='age',
        ),
    ]
