# Generated by Django 4.0.1 on 2022-01-06 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education_experience_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
